networks:
  default:
    driver: bridge
    name: roboshop
    external: true

services:
  mongodb:
    image: kntheun/mongodb:v1
    container_name: mongodb

  catalogue:
    image: kntheun/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb

  redis:
    image: redis:7.0
    container_name: redis

  user:
    image: kntheun/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis

  cart:
    image: kntheun/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis

  mysql:
    image: kntheun/mysql:v1
    container_name: mysql

  shipping:
    image: kntheun/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
